export { IconSearch } from './IconSearch';
export { IconAirplane } from './IconAirplane';
export { IconMenu } from './IconMenu';
export { IconClose } from './IconClose';
export { IconPrevArrow } from './IconPrevArrow';
export { IconNextArrow } from './IconNextArrow';
export { IconFacebook } from './IconFacebook';
export { IconTwitter } from './IconTwitter';
export { IconInstagram } from './IconInstagram';